### ISSUE TITLE
Suggestion: Add section for 'Talks'

### ISSUE THREAD

**Issue by iayanpahwa** [adafruit/awesome-circuitpython#11]
It will be good to have a curated list of CircuitPython talks from different speakers around the world, delivered during any conference, meetup or any other event.

**Comment by tannewt** [comment]
Good idea! Want to make a PR to start it?

**Comment by iayanpahwa** [comment]
@tannewt sure thing! coming up tomorrow :)

**Comment by iayanpahwa** [comment]
@tannewt PR Generated - Adding talks sections #12

**Comment by iayanpahwa** [comment]
PR merged, closing this issue.
