### ISSUE TITLE
Video File does not display at https://circuitpython.org/awesome

### ISSUE THREAD

**Issue by prcutler** [adafruit/awesome-circuitpython#33]
The video that is embedded in the README on line 11 displays fine if you're viewing the Awesome List on Github.

But if you view it at https://circuitpython.org/awesome it displays the URL and not the video file:

`https://user-images.githubusercontent.com/1685947/115119719-d6e21f00-9f77-11eb-84bf-3f7af59948a3.mov`

We should decide which site is the main site and whether the video should be included or not.  Or if it can be embedded in HTML instead?

**Comment by FoamyGuy** [comment]
I think the page is rendered from this file here: https://github.com/adafruit/circuitpython-org/blob/master/awesome.html int he CircuitPython_Org repo. 

It might make sense to move this issue over to that repo.

Only took a quick peek into it, but looks to me like the gets rendered via the Jekyll build process. The template loads in the contents of the md file and renders it using a `markdownify` template tag. I'm not sure if that functionality specifically comes from Jekyll or is a feature of whatever the template language is (looks like Jinja2 to me, but possibly something else, there are some similar ones I think).

The best way to solve this is probably see if whatever provides that `markdownify` tag has the option to include video rendering. Or try to add it if not, as you noted it should be pretty straight forward for it to render a <video> html element with that URL as the source. 

Or if those are not possible for some reason it could be hardcoded into the HTML page but I think the order of the page would end up having to change a little bit. The video would have to go either above or below the md content I think.
