### ISSUE TITLE
Awesome-List on CircuitPython.org needs to be updated

### ISSUE THREAD

**Issue by prcutler** [adafruit/awesome-circuitpython#41]
Hi,

It looks to me that the Awesome List Github Repo and the [website](https://circuitpython.org/awesome) are out of sync, with the Github repo being newer.  Is the website supposed to auto-update from git commits or does it need to be manually updated?

Thanks!

**Comment by jepler** [comment]
@TheKitty I added a PR in circuitpython-org to fix this, but I guess "updating the submodule" either needs to go on your checklist when merging PRs in this repo, or we need to find a way to automate it. Feel free to chat me up about what this means, it may be something that needs git/github commandline work to do each time.

**Comment by jepler** [comment]
@prcutler thanks, good catch!
