### ISSUE TITLE
dead links 

### ISSUE THREAD

**Issue by z00rat** [adafruit/awesome-circuitpython#44]
hi,
i found some problem with this repo.

---

list of dead links:
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L98
   https://electroniccats.com/producto/meowmeow/ and https://electroniccats.com/producto/catwan_usb-stick/ and https://electroniccats.com/store/bast-wifi/
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L103
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L104
   https://www.tindie.com/products/deshipu/ugame-10-python-game-console-kit/
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L119
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L117
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L131
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L139
  https://bdmicro.com/products/vina-d21
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L152
   https://www.oakdev.tech/store/p7/CP-Sapling-m0-development-board.html#/
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L205
- https://github.com/adafruit/awesome-circuitpython/blob/076bfa61813df46026f3eac97f351edcaa392842/README.md?plain=1#L243
-

**Comment by TheKitty** [comment]
Thank you. The pace of new boards exceeds our ability to update the awesome list, so the list is being revamped to have pointers to circuitpython.org.

Thank you for reviewing the list and if you find more, please issue a pull request or open a new issue.
