### ISSUE TITLE
Where to put PewPew?

### ISSUE THREAD

**Issue by deshipu** [adafruit/awesome-circuitpython#49]
Hi,

I would like to add a link to the http://pewpew.rtfd.io documentation in here, but I'm at a loss where it would belong. PewPew started as a featherwing for making simple games, but it gradually evolved into several independent devices, and a whole lot of tutorials, guides and example games. I use it for running Python programming workshop, and I think it could be a very useful tool for educators, but where to put it? Under "Guides", because there are tutorials? Under "Code", because of the library and the example games? Under "Frameworks", because it's its own ecosystem? Under hardware, because of all the devices designed for it?

**Comment by dhalbert** [comment]
I think Frameworks makes sense. It is an ecosystem. There aren't really other examples exactly like it in Frameworks. You could put multiple links in Frameworks if there is more than one "top level".

I think some of the things in Frameworks could really be a new category like "Workflow" or "Programming Tools".
